### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by kekyo** [persimmon-projects/Persimmon.VisualStudio.TestExplorer#1]
- Combinates persimmon core library version changes merge to Persimmon/master.
  - TestExplorer's version set to 2.0.0?
  - Next generation version set to 3.0.0?
- VSIX icon is lesser.
  - Strongly icon outlined, more soft or apply another effects...
- Convert vdproj to WiX
  - AppVeyor's CI failed for using vdproj (MSBuild cannot support non-xml based project?)
  - TEST: Windows installer project to WiX converter available, but evaluation-trail ? (https://visualstudiogallery.msdn.microsoft.com/0f8ff662-c844-4c3c-9c7b-b170cea16baf)

**Comment by kekyo** [comment]
- Remove FSharp.Compiler.Service.ProjectCracker
  - ProjectCracker is out of boxed (.exe) and depends MSBuild.Tasks.
  - Cannot identicate project configuration (Debug or Release or etc...) in AST discovering, so got non perfect result with ProjectCracker.
  - May easy self parse/traverse fsproj...

**Comment by kekyo** [comment]
- vdproj --> WiX
  - How to (vsix) http://www.codeproject.com/Articles/873395/Installing-VSIX-package-via-WiX-installer
  - TASK: include vsix, GAC registration, redraw banner.
  - Setup.Helper can eliminate?
  - Auto or manual build? (can CI? versioning?)

**Comment by kekyo** [comment]
- Visual Studio Gallery
  - Will require manual input (not auto lookup) version for registering EXE: https://files.gitter.im/persimmon-projects/ja/RbwA/blob

**Comment by pocketberserker** [comment]
old issue
